[package]
name = "ansi-parser"
description = "A library using nom for parsing ANSI Escape Codes"
homepage = "https://gitlab.com/DavidBittner/ansi-parser"
version = "0.1.0"
authors = ["David Bittner <bittneradave@gmail.com>"]
edition = "2018"

license-file = "LICENSE" 

[dependencies]
nom = "4.2.3"
num-traits = "0.2"
num-derive = "0.2"
